### ISSUE TITLE
Debounce bug for SAVE

### ISSUE THREAD

**Issue by localhosthack0r** [g4eml/Bullseye-Calibrator#1]
Hi,
I don't know if this has practical relevance, but when reading through your code, I saw this bug:
https://github.com/g4eml/Bullseye-Calibrator/blob/f40e6ebdf924d636e243ee5be80b13e0547c1966/Bullseye_Calibrator.ino#L124

if (debounce=20) 
is an assignment and will always return true.

**Comment by g4eml** [comment]
Thanks, typo Corrected.
