### ISSUE TITLE
Generate 23mm POTY Adaptor variant

### ISSUE THREAD

**Issue by m1dst** [g4eml/Bullseye-Calibrator#2]
Would it be possible to generate and upload an adapter for a 23mm tube?  DJ7GP uses a 23mm aluminum tube and your adapter is designed for the normal 22mm copper heating pipe.  It would be really great if you could help.

**Comment by m1dst** [comment]
I managed to modify your existing STL so not required by me anymore.

**Comment by g4eml** [comment]
I have added a 23mm version for anyone that needs it.
